### ISSUE TITLE
re-use pickled trials from a different run

### ISSUE THREAD

**Issue by jiri-hostas** [MilesCranmer/easy_distributed_hyperopt#1]
Hi Miles,

I have got two questions.

1)  When I try to re-use a pickled trials file from a different run, I get an error at the line: "n_trials = trials_obj['n']". Is it possible to reuse results from the old runs made with a different script?
2) I don't understand why do you use the structure "{'trials': save_trials, 'n': n} instead of just trials. Would you mind hinting me in a right direction?

Thank you for your reply and keep up your good work! Cheers,

Jiri

**Comment by MilesCranmer** [comment]
Hi Jiri,

Thanks!

1. With the code as it's currently set up, all the .pkl files should contain {'trials': trials, 'n': number_of_trials}. If you are saving a trials object from a different file, make sure to format it like this.
2. You could modify the example code - it's not so much a python package as it is an example of how you can do this sort of thing. However, currently it is set to that format. You are right that you don't need both the trials object and its length - it's redundant info.

Best,
Miles
